### ISSUE TITLE
mail sending error on docker

### ISSUE THREAD

**Issue by ser** [p2-inc/phasetwo-containers#6] opened 2022-12-23 18:39 UTC
Hi, I deployed my service on "original" quay.io/keycloak/keycloak docker image, and later just changed image to quay.io/phasetwo/phasetwo-keycloak and it's impossible to send mail on it.  When I switch back to "original" - mail works correctly. 

Phasetwo image gives this error:

```
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)                                                                                                     
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)                                                                                              
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)                                                                                        
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)                                                                                           
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)                                                                                           
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)                                                                                                                     
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)                                                                                                
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)                                                                                                               
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)                                                                                          
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)                                                                                          
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)                                                                                                                     
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)                                                                                                
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)                                                                                                               
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)                                                                                                     
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)                                                                                                     
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)                                                                                                                     
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)                                                                                                
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)                                                                                                               
        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)                                                           
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:564)                                                                                                   
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)                                                                                                        
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)                                                                                                  
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)                                                                                                                     
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)                                                                                                 
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)                                                                                                    
        at java.base/java.lang.Thread.run(Thread.java:829)                                                                                                                                          
java.lang.NullPointerException                   
        at org.keycloak.services.resources.admin.RealmAdminResource.testSMTPConnection(RealmAdminResource.java:953)                                                                        [73/3116]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
        at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
        at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
        at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
        at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:564)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478) 
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
2022-12-23 18:25:57,992 ERROR [org.keycloak.services.resources.admin.RealmAdminResource] (executor-thread-63) Failed to send email 
 null
```

I am using current latest docker images of both, phasetwo and "original" one.

**Comment by xgp** [comment] 2022-12-24 07:58
@ser Thanks for the report:
1. Can you post the whole log, along with context around the exception. 
2. What startup command are you using?
3. What theme did you select for email?
If I know those things, I can try to reproduce.

**Comment by Andrius0124** [comment] 2023-01-04 05:31
Same problem.
Here is the dockerfile: 
`
FROM quay.io/phasetwo/phasetwo-keycloak:20.0.2.1671556844 as builder

ENV KC_DB=postgres
ENV KC_HTTP_RELATIVE_PATH=/auth
ENV KC_CACHE_CONFIG_FILE=cache-ispn-jdbc-ping.xml

COPY ./conf/cache-ispn-jdbc-ping.xml /opt/keycloak/conf/cache-ispn-jdbc-ping.xml

RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/phasetwo/phasetwo-keycloak:20.0.2.1671556844

COPY --from=builder /opt/keycloak/lib/quarkus/ /opt/keycloak/lib/quarkus/
COPY --from=builder /opt/keycloak/providers/ /opt/keycloak/providers/

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "-v", "start", "--optimized" ]
`

**Comment by xgp** [comment] 2023-01-04 18:08
@Andrius0124 Thanks for the full context. It seems that when you don't specify the new `EmailTemplateProvider` as a startup parameter, it can't load the default. Perhaps this is because it is included in the building of the base image, and makes the default inacessible. I will try to debug why, but in the meantime, please try the following docker entrypoint"
```
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "-v", "start", "--optimized --spi-email-template-provider=freemarker-plus-mustache --spi-email-template-freemarker-plus-mustache-enabled=true" ]
```

**Comment by rvmourik** [comment] 2023-03-08 14:05
Hi There,

I have the same issue, but I don't use the freemarker/mustache setting. I set the email theme to "base", however every test email I try to send results in the same error as the original posted issue. ` Failed to send email  null`.

Is there any news why this isn't working?

**Comment by xgp** [comment] 2023-03-08 14:22
@rvmourik did you use the `--spi-email-template-provider=freemarker-plus-mustache --spi-email-template-freemarker-plus-mustache-enabled=true` flags at startup?

**Comment by rvmourik** [comment] 2023-03-08 14:23
Hi @xgp,

Yes, I believe so.

This is my entrypoint

```
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "-v", "start", "--optimized", "--spi-theme-static-max-age=-1", "--spi-theme-cache-themes=false", "--spi-theme-cache-templates=false", "--spi-email-template-provider=freemarker-plus-mustache", "--spi-email-template-freemarker-plus-mustache-enabled=true" ]
```

**Comment by xgp** [comment] 2023-03-08 14:27
@rvmourik thanks for the detail. I'll try that entrypoint myself and report back.

**Comment by rvmourik** [comment] 2023-03-08 14:28
> @rvmourik thanks for the detail. I'll try that entrypoint myself and report back.

Thanks

**Comment by xgp** [comment] 2023-03-08 15:35
Running with that entrypoint, setting the email theme to `base`, I send a test email from the **Realm Settings** -> **Email** page in the admin and it works. 

```
kc.sh start --optimized --spi-email-template-provider=freemarker-plus-mustache --spi-email-template-freemarker-plus-mustache-enabled=true --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false --hostname-strict=false
```

If you can send me a bit more about your setup, I can try to debug more. Are you running a custom docker image?

**Comment by xgp** [comment] 2023-04-24 16:33
Closing pending additional information.

**Closed by xgp** 2023-04-24 16:33 UTC

**Comment by egdelwonk** [comment] 2023-05-24 20:46
I'm seeing similar behavior with the latest image. Using docker-compose and set the 


### Logs
When sending a test e-mail with Test Connection button on http://localhost:8080/admin/master/console/#/master/realm-settings/email

```
keycloak-compose-keycloak-1  | java.lang.NullPointerException: Cannot invoke "org.keycloak.email.EmailTemplateProvider.sendSmtpTestEmail(java.util.Map, org.keycloak.models.UserModel)" because the return value of "org.keycloak.models.KeycloakSession.getProvider(java.lang.Class)" is null
keycloak-compose-keycloak-1  |  at org.keycloak.services.resources.admin.RealmAdminResource.testSMTPConnection(RealmAdminResource.java:938)
keycloak-compose-keycloak-1  |  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
keycloak-compose-keycloak-1  |  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
keycloak-compose-keycloak-1  |  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
keycloak-compose-keycloak-1  |  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
keycloak-compose-keycloak-1  |  at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
keycloak-compose-keycloak-1  |  at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
keycloak-compose-keycloak-1  |  at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
keycloak-compose-keycloak-1  |  at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
keycloak-compose-keycloak-1  |  at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
keycloak-compose-keycloak-1  |  at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
keycloak-compose-keycloak-1  |  at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
keycloak-compose-keycloak-1  |  at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
keycloak-compose-keycloak-1  |  at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
keycloak-compose-keycloak-1  |  at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
keycloak-compose-keycloak-1  |  at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
keycloak-compose-keycloak-1  |  at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
keycloak-compose-keycloak-1  |  at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
keycloak-compose-keycloak-1  |  at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
keycloak-compose-keycloak-1  |  at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
keycloak-compose-keycloak-1  |  at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
keycloak-compose-keycloak-1  |  at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
keycloak-compose-keycloak-1  |  at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
keycloak-compose-keycloak-1  |  at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
keycloak-compose-keycloak-1  |  at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
keycloak-compose-keycloak-1  |  at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
keycloak-compose-keycloak-1  |  at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
keycloak-compose-keycloak-1  |  at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
keycloak-compose-keycloak-1  |  at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
keycloak-compose-keycloak-1  |  at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
keycloak-compose-keycloak-1  |  at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
keycloak-compose-keycloak-1  |  at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
keycloak-compose-keycloak-1  |  at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
keycloak-compose-keycloak-1  |  at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
keycloak-compose-keycloak-1  |  at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
keycloak-compose-keycloak-1  |  at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
keycloak-compose-keycloak-1  |  at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
keycloak-compose-keycloak-1  |  at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
keycloak-compose-keycloak-1  |  at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
keycloak-compose-keycloak-1  |  at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
keycloak-compose-keycloak-1  |  at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
keycloak-compose-keycloak-1  |  at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
keycloak-compose-keycloak-1  |  at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
keycloak-compose-keycloak-1  |  at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
keycloak-compose-keycloak-1  |  at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
keycloak-compose-keycloak-1  |  at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
keycloak-compose-keycloak-1  |  at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
keycloak-compose-keycloak-1  |  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
keycloak-compose-keycloak-1  |  at java.base/java.lang.Thread.run(Thread.java:833)
keycloak-compose-keycloak-1  | 2023-05-24 20:45:40,848 ERROR [org.keycloak.services.resources.admin.RealmAdminResource] (executor-thread-13) Failed to send email

keycloak-compose-keycloak-1  |  null
```

### Dockerfile
```dockerfile
FROM quay.io/phasetwo/phasetwo-keycloak:latest as builder

COPY ./conf/cache-ispn-jdbc-ping.xml /opt/keycloak/conf/cache-ispn-jdbc-ping.xml

RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/phasetwo/phasetwo-keycloak:latest

COPY --from=builder /opt/keycloak/lib/quarkus/ /opt/keycloak/lib/quarkus/
COPY --from=builder /opt/keycloak/providers/ /opt/keycloak/providers/


ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "-v", "start", "\
  --optimized \
  --spi-email-template-provider=freemarker-plus-mustache \
  --spi-email-template-freemarker-plus-mustache-enabled=true \
  --spi-theme-cache-themes=false"]
```

**Comment by xgp** [comment] 2023-05-24 21:05
I think the missing piece is that you need to use the spi flags in the `build` command as well. E.g.
```
RUN /opt/keycloak/bin/kc.sh build --spi-email-template-provider=freemarker-plus-mustache --spi-email-template-freemarker-plus-mustache-enabled=true --spi-theme-cache-themes=false 
```
I tested that with your examples and it works.

**Comment by egdelwonk** [comment] 2023-05-24 21:10
@xgp That did the trick. Thank you so much.

**Comment by matheushent** [comment] 2024-06-27 15:47
> Running with that entrypoint, setting the email theme to `base`, I send a test email from the **Realm Settings** -> **Email** page in the admin and it works.
> 
> ```
> kc.sh start --optimized --spi-email-template-provider=freemarker-plus-mustache --spi-email-template-freemarker-plus-mustache-enabled=true --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false --hostname-strict=false
> ```
> 
> If you can send me a bit more about your setup, I can try to debug more. Are you running a custom docker image?

For anyone falling here, I can confirm this works in k8s environment.
